"""survey-currents: surface-current and water-temperature acquisition engine.

Acquire hourly current-vector (u/v) and water-temperature fields from
operational hydrodynamic forecast models — NOAA Operational Forecast
Systems (anonymous AWS S3) and the Copernicus Marine Service — plus
NOAA GLSEA satellite-derived daily sea-surface temperature and
lake-average temperature series, into one canonical
:class:`~currents.models.CurrentField` model (and the SST-focused
:class:`~currents.glsea.GlseaField`) with provenance, COG export, and
survey-suite interoperability.

Engine core is stdlib+numpy. Heavy dependencies (xarray, boto3,
netCDF4, copernicusmarine, rasterio) are lazy optional imports; every
public function that needs one raises an actionable ImportError naming
the ``pip install`` extra.
"""

from __future__ import annotations

__version__ = "0.12.0"

from .basemaps import (GEBCO_NATIVE_ARCSEC, GEBCO_VERSION, GEBCO_ZIP_URL,
                       NATURAL_EARTH_LAYERS, NATURAL_EARTH_SCALES, TopoField,
                       ensure_gebco_tile, ensure_naturalearth_zip,
                       fetch_gebco, fetch_naturalearth, gebco_tiles_for_bbox,
                       synthetic_naturalearth)
from .currents_global import (
    CMEMS_CURRENTS_PRESET, CMEMS_CURRENTS_VARIABLES, OSCAR_COLLECTIONS,
    OSCAR_DIM_ORDER, OSCAR_FINAL_MAX_AGE_DAYS, OSCAR_GRANULE_STEMS,
    OSCAR_INTERIM_MAX_AGE_DAYS, OSCAR_LAT_MAX, OSCAR_LAT_MIN, OSCAR_LON_MAX,
    OSCAR_LON_MIN, OSCAR_OPENDAP_PATTERN, OSCAR_RES, OSCAR_START,
    CredentialsMissing as OscarCredentialsMissing, cmems_currents_synthetic,
    cmr_search_oscar_granules, fetch_cmems_currents, fetch_oscar,
    oscar_collection_for, oscar_granule_title, oscar_index_windows,
    oscar_lon_windows, oscar_service_url, oscar_subset_urls, oscar_synthetic)
from .era5 import (ERA5_DATASET, ERA5_RES, ERA5_START, ERA5_VARIABLES,
                   CredentialsMissing as Era5CredentialsMissing, Era5Field,
                   era5_area_windows, era5_cds_names, era5_month_chunks,
                   era5_request, era5_sample_plan, fetch_era5,
                   normalize_era5_variables, validate_era5_bbox)
from .glsea import (LAKE_COLUMNS, GlseaField, LakeSeries,
                    fetch_glsea_lake_averages, fetch_glsea_sst,
                    glsea_averages_url, glsea_sst_url, validate_glsea_bbox)
from .imerg import (IMERG_ACCUMULATIONS, IMERG_BASE, IMERG_COLLECTIONS,
                    IMERG_FILL, IMERG_LATENCY, IMERG_RES, IMERG_START,
                    IMERG_UNITS_DAILY, IMERG_UNITS_NATIVE, IMERG_VERSION,
                    CredentialsMissing as ImergCredentialsMissing, RainField,
                    accumulate_daily, fetch_imerg, imerg_file_url,
                    imerg_granule_name, imerg_index_windows,
                    imerg_sample_days, normalize_imerg_accumulate,
                    normalize_imerg_run)
from .models import OFS_REGISTRY, CurrentField, OfsModel, get_ofs_model
from .provenance import PROVENANCE_VERSION, read_provenance, verify_provenance, write_provenance
from .sst_global import (CMR_GRANULE_SEARCH, CredentialsMissing, SstField,
                         cmr_search_mur_granules, earthdata_credentials,
                         fetch_mur, fetch_oisst, mur_granule_title,
                         mur_match_granules, mur_opendap_url, mur_subset_urls,
                         oisst_lon_windows, oisst_sst_urls,
                         validate_sst_bbox)
from .sea_ice import (HUGHES_A, HUGHES_E2, NSIDC_BASE, NSIDC_CELL_M,
                       NSIDC_CONC_SCALE, NSIDC_FLAG_LABELS, NSIDC_FLAGS,
                       NSIDC_GRIDS, NSIDC_G02135_PATH, NSIDC_START,
                       NSIDC_VERSION, IceField, decode_concentration,
                       fetch_nsidc_sic, nsidc_conc_url, pick_hemisphere,
                       ps_forward, read_concentration_geotiff,
                       reproject_to_latlon, resolve_native_grid, target_grid,
                       validate_ice_bbox)
from .grace import (GRACE_BASELINE, GRACE_EPOCH, GRACE_MASK_FILE,
                     GRACE_MASK_URL, GRACE_MAX_CACHE_AGE_DAYS,
                     GRACE_PRODUCT, GRACE_PRODUCT_VERSION, GRACE_RECORD_START,
                     GRACE_SOLUTION_FILE, GRACE_SOLUTION_URL, GRACE_UNITS,
                     WaterField, ensure_grace_files, fetch_grace,
                     grace_cache_dir, grace_file_url)
from .storms import (IBTRACS_ALL_FILE, IBTRACS_NC_DIR,
                     IBTRACS_SINCE1980_FILE, IBTRACS_START_ALL,
                     IBTRACS_START_SINCE1980, IBTRACS_VERSION, SSHS_CATEGORIES,
                     SSHS_COLORS, SSHS_LABELS, StormField, StormTrack,
                     ensure_ibtracs_file, fetch_ibtracs, ibtracs_filename,
                     ibtracs_url, sshs_category, storm_cache_dir)

__all__ = [
    "CurrentField",
    "OfsModel",
    "OFS_REGISTRY",
    "get_ofs_model",
    "GlseaField",
    "LakeSeries",
    "LAKE_COLUMNS",
    "fetch_glsea_sst",
    "fetch_glsea_lake_averages",
    "glsea_sst_url",
    "glsea_averages_url",
    "validate_glsea_bbox",
    "SstField",
    "CredentialsMissing",
    "CMR_GRANULE_SEARCH",
    "cmr_search_mur_granules",
    "mur_match_granules",
    "fetch_oisst",
    "fetch_mur",
    "oisst_sst_urls",
    "oisst_lon_windows",
    "IceField",
    "fetch_nsidc_sic",
    "nsidc_conc_url",
    "pick_hemisphere",
    "validate_ice_bbox",
    "StormField",
    "StormTrack",
    "WaterField",
    "fetch_grace",
    "ensure_grace_files",
    "grace_cache_dir",
    "grace_file_url",
    "GRACE_PRODUCT",
    "GRACE_PRODUCT_VERSION",
    "GRACE_SOLUTION_FILE",
    "GRACE_SOLUTION_URL",
    "GRACE_MASK_FILE",
    "GRACE_MASK_URL",
    "GRACE_EPOCH",
    "GRACE_RECORD_START",
    "GRACE_BASELINE",
    "GRACE_UNITS",
    "GRACE_MAX_CACHE_AGE_DAYS",
    "fetch_ibtracs",
    "ensure_ibtracs_file",
    "ibtracs_url",
    "ibtracs_filename",
    "storm_cache_dir",
    "sshs_category",
    "IBTRACS_VERSION",
    "IBTRACS_NC_DIR",
    "IBTRACS_SINCE1980_FILE",
    "IBTRACS_ALL_FILE",
    "IBTRACS_START_SINCE1980",
    "IBTRACS_START_ALL",
    "SSHS_CATEGORIES",
    "SSHS_COLORS",
    "SSHS_LABELS",
    "decode_concentration",
    "read_concentration_geotiff",
    "reproject_to_latlon",
    "resolve_native_grid",
    "ps_forward",
    "target_grid",
    "NSIDC_BASE",
    "NSIDC_G02135_PATH",
    "NSIDC_VERSION",
    "NSIDC_START",
    "NSIDC_GRIDS",
    "NSIDC_FLAGS",
    "NSIDC_FLAG_LABELS",
    "NSIDC_CONC_SCALE",
    "NSIDC_CELL_M",
    "HUGHES_A",
    "HUGHES_E2",
    "RainField",
    "ImergCredentialsMissing",
    "IMERG_BASE",
    "IMERG_VERSION",
    "IMERG_COLLECTIONS",
    "IMERG_START",
    "IMERG_LATENCY",
    "IMERG_RES",
    "IMERG_UNITS_DAILY",
    "IMERG_UNITS_NATIVE",
    "IMERG_FILL",
    "IMERG_ACCUMULATIONS",
    "fetch_imerg",
    "accumulate_daily",
    "imerg_granule_name",
    "imerg_file_url",
    "imerg_sample_days",
    "imerg_index_windows",
    "normalize_imerg_run",
    "normalize_imerg_accumulate",
    "mur_granule_title",
    "mur_opendap_url",
    "mur_subset_urls",
    "earthdata_credentials",
    "validate_sst_bbox",
    "Era5Field",
    "Era5CredentialsMissing",
    "ERA5_DATASET",
    "ERA5_START",
    "ERA5_RES",
    "ERA5_VARIABLES",
    "fetch_era5",
    "normalize_era5_variables",
    "validate_era5_bbox",
    "era5_area_windows",
    "era5_cds_names",
    "era5_month_chunks",
    "era5_request",
    "era5_sample_plan",
    "OSCAR_COLLECTIONS",
    "OSCAR_GRANULE_STEMS",
    "OSCAR_OPENDAP_PATTERN",
    "OSCAR_RES",
    "OSCAR_LON_MIN",
    "OSCAR_LON_MAX",
    "OSCAR_LAT_MIN",
    "OSCAR_LAT_MAX",
    "OSCAR_DIM_ORDER",
    "OSCAR_START",
    "OSCAR_FINAL_MAX_AGE_DAYS",
    "OSCAR_INTERIM_MAX_AGE_DAYS",
    "CMEMS_CURRENTS_PRESET",
    "CMEMS_CURRENTS_VARIABLES",
    "OscarCredentialsMissing",
    "fetch_oscar",
    "fetch_cmems_currents",
    "oscar_collection_for",
    "oscar_granule_title",
    "oscar_service_url",
    "cmr_search_oscar_granules",
    "oscar_lon_windows",
    "oscar_index_windows",
    "oscar_subset_urls",
    "oscar_synthetic",
    "cmems_currents_synthetic",
    "TopoField",
    "fetch_gebco",
    "fetch_naturalearth",
    "ensure_gebco_tile",
    "ensure_naturalearth_zip",
    "gebco_tiles_for_bbox",
    "synthetic_naturalearth",
    "GEBCO_VERSION",
    "GEBCO_ZIP_URL",
    "GEBCO_NATIVE_ARCSEC",
    "NATURAL_EARTH_SCALES",
    "NATURAL_EARTH_LAYERS",
    "PROVENANCE_VERSION",
    "read_provenance",
    "verify_provenance",
    "write_provenance",
    "__version__",
]
