"""survey-currents: surface-current and water-temperature acquisition engine.

Acquire hourly current-vector (u/v) and water-temperature fields from
operational hydrodynamic forecast models — NOAA Operational Forecast
Systems (anonymous AWS S3) and the Copernicus Marine Service — plus
NOAA GLSEA satellite-derived daily sea-surface temperature and
lake-average temperature series, into one canonical
:class:`~currents.models.CurrentField` model (and the SST-focused
:class:`~currents.glsea.GlseaField`) with provenance, COG export, and
survey-suite interoperability.

Engine core is stdlib+numpy. Heavy dependencies (xarray, boto3,
netCDF4, copernicusmarine, rasterio) are lazy optional imports; every
public function that needs one raises an actionable ImportError naming
the ``pip install`` extra.
"""

from __future__ import annotations

# Single source of truth for the package version: the installed
# distribution metadata (written from pyproject.toml at install time).
# This never goes stale the way a hand-edited string does — which is
# how __version__ silently reported 0.14.0 through the 0.15.x releases.
try:
    from importlib.metadata import PackageNotFoundError, version

    __version__ = version("survey-currents")
except Exception:  # pragma: no cover - editable/uninstalled checkout
    try:
        __version__ = version("survey_currents")
    except PackageNotFoundError:
        __version__ = "0.0.0+unknown"

from .basemaps import (GEBCO_NATIVE_ARCSEC, GEBCO_VERSION, GEBCO_ZIP_URL,
                       NATURAL_EARTH_LAYERS, NATURAL_EARTH_SCALES, TopoField,
                       ensure_gebco_tile, ensure_naturalearth_zip,
                       fetch_gebco, fetch_naturalearth, gebco_tiles_for_bbox,
                       synthetic_naturalearth)
from .currents_global import (
    CMEMS_CURRENTS_PRESET, CMEMS_CURRENTS_VARIABLES, OSCAR_COLLECTIONS,
    OSCAR_DIM_ORDER, OSCAR_FINAL_MAX_AGE_DAYS, OSCAR_GRANULE_STEMS,
    OSCAR_INTERIM_MAX_AGE_DAYS, OSCAR_LAT_MAX, OSCAR_LAT_MIN, OSCAR_LON_MAX,
    OSCAR_LON_MIN, OSCAR_OPENDAP_PATTERN, OSCAR_RES, OSCAR_START,
    CredentialsMissing as OscarCredentialsMissing, cmems_currents_synthetic,
    cmr_search_oscar_granules, fetch_cmems_currents, fetch_oscar,
    oscar_collection_for, oscar_granule_title, oscar_index_windows,
    oscar_lon_windows, oscar_service_url, oscar_subset_urls, oscar_synthetic)
from .era5 import (ERA5_DATASET, ERA5_RES, ERA5_START, ERA5_VARIABLES,
                   CredentialsMissing as Era5CredentialsMissing, Era5Field,
                   era5_area_windows, era5_cds_names, era5_month_chunks,
                   era5_request, era5_sample_plan, fetch_era5,
                   normalize_era5_variables, validate_era5_bbox)
from .glsea import (LAKE_COLUMNS, GlseaField, LakeSeries,
                    fetch_glsea_lake_averages, fetch_glsea_sst,
                    glsea_averages_url, glsea_sst_url, validate_glsea_bbox)
from .imerg import (IMERG_ACCUMULATIONS, IMERG_BASE, IMERG_COLLECTIONS,
                    IMERG_FILL, IMERG_LATENCY, IMERG_RES, IMERG_START,
                    IMERG_UNITS_DAILY, IMERG_UNITS_NATIVE, IMERG_VERSION,
                    CredentialsMissing as ImergCredentialsMissing, RainField,
                    accumulate_daily, fetch_imerg, imerg_file_url,
                    imerg_granule_name, imerg_index_windows,
                    imerg_sample_days, normalize_imerg_accumulate,
                    normalize_imerg_run)
from .models import OFS_REGISTRY, CurrentField, OfsModel, get_ofs_model
from .provenance import PROVENANCE_VERSION, read_provenance, verify_provenance, write_provenance
from .sst_global import (CMR_GRANULE_SEARCH, CredentialsMissing, SstField,
                         cmr_search_mur_granules, earthdata_credentials,
                         fetch_mur, fetch_oisst, mur_granule_title,
                         mur_match_granules, mur_opendap_url, mur_subset_urls,
                         oisst_lon_windows, oisst_sst_urls,
                         validate_sst_bbox)
from .sea_ice import (HUGHES_A, HUGHES_E2, NSIDC_BASE, NSIDC_CELL_M,
                       NSIDC_CONC_SCALE, NSIDC_FLAG_LABELS, NSIDC_FLAGS,
                       NSIDC_GRIDS, NSIDC_G02135_PATH, NSIDC_START,
                       NSIDC_VERSION, IceField, decode_concentration,
                       fetch_nsidc_sic, nsidc_conc_url, pick_hemisphere,
                       ps_forward, read_concentration_geotiff,
                       reproject_to_latlon, resolve_native_grid, target_grid,
                       validate_ice_bbox)
from .grace import (GRACE_BASELINE, GRACE_EPOCH, GRACE_MASK_FILE,
                     GRACE_MASK_URL, GRACE_MAX_CACHE_AGE_DAYS,
                     GRACE_PRODUCT, GRACE_PRODUCT_VERSION, GRACE_RECORD_START,
                     GRACE_SOLUTION_FILE, GRACE_SOLUTION_URL, GRACE_UNITS,
                     WaterField, ensure_grace_files, fetch_grace,
                     grace_cache_dir, grace_file_url)
from .storms import (IBTRACS_ALL_FILE, IBTRACS_NC_DIR,
                     IBTRACS_SINCE1980_FILE, IBTRACS_START_ALL,
                     IBTRACS_START_SINCE1980, IBTRACS_VERSION, SSHS_CATEGORIES,
                     SSHS_COLORS, SSHS_LABELS, StormField, StormTrack,
                     ensure_ibtracs_file, fetch_ibtracs, ibtracs_filename,
                     ibtracs_url, sshs_category, storm_cache_dir)
from .streamgages import (FT_TO_M, FT3S_TO_M3S, USGS_DV_BASE,
                          USGS_MAX_CACHE_AGE_DAYS, USGS_MISSING,
                          USGS_PARAMETERS, USGS_RECORD_START, USGS_SITE_BASE,
                          USGS_SITE_LIMIT, GageField, GageRecord,
                          dv_request_url, fetch_usgs, site_inventory_url,
                          usgs_cache_dir)
from .earthquakes import (COMCAT_COUNT_BASE, COMCAT_DEPTH_BINS_KM,
                         COMCAT_EVENT_BASE, COMCAT_FDSN_LIMIT,
                         COMCAT_MAX_CACHE_AGE_DAYS, COMCAT_PAGE_SIZE,
                         COMCAT_RECORD_START, QuakeEvent, QuakeField,
                         comcat_cache_dir, event_count_url,
                         event_query_url, fetch_earthquakes)
from .oceancolor import (CMEMS_OCEANCOLOR_PRODUCT,
                         CMEMS_OCEANCOLOR_VARIABLE,
                         COASTWATCH_DATASETS, COASTWATCH_ERDDAP_BASE,
                         OBPG_CMR_COLLECTION_ID, OBPG_CMR_SHORT_NAME,
                         OBPG_DIRECTACCESS_BASE, OBPG_RECORD_START,
                         OCEANCOLOR_LAT_MAX, OCEANCOLOR_LAT_MIN,
                         OCEANCOLOR_LON_MAX, OCEANCOLOR_LON_MIN,
                         OCEANCOLOR_MAX_CACHE_AGE_DAYS, OCEANCOLOR_UNITS,
                         OCEANCOLOR_VAR, OceanColorField,
                         fetch_oceancolor, fetch_oceancolor_cmems,
                         fetch_oceancolor_coastwatch, fetch_oceancolor_obpg,
                         main_demo, obpg_file_names, oceancolor_cache_dir,
                         oceancolor_urls)

__all__ = [
    "CurrentField",
    "OfsModel",
    "OFS_REGISTRY",
    "get_ofs_model",
    "GlseaField",
    "LakeSeries",
    "LAKE_COLUMNS",
    "fetch_glsea_sst",
    "fetch_glsea_lake_averages",
    "glsea_sst_url",
    "glsea_averages_url",
    "validate_glsea_bbox",
    "SstField",
    "CredentialsMissing",
    "CMR_GRANULE_SEARCH",
    "cmr_search_mur_granules",
    "mur_match_granules",
    "fetch_oisst",
    "fetch_mur",
    "oisst_sst_urls",
    "oisst_lon_windows",
    "IceField",
    "fetch_nsidc_sic",
    "nsidc_conc_url",
    "pick_hemisphere",
    "validate_ice_bbox",
    "StormField",
    "StormTrack",
    "WaterField",
    "fetch_grace",
    "ensure_grace_files",
    "grace_cache_dir",
    "grace_file_url",
    "GRACE_PRODUCT",
    "GRACE_PRODUCT_VERSION",
    "GRACE_SOLUTION_FILE",
    "GRACE_SOLUTION_URL",
    "GRACE_MASK_FILE",
    "GRACE_MASK_URL",
    "GRACE_EPOCH",
    "GRACE_RECORD_START",
    "GRACE_BASELINE",
    "GRACE_UNITS",
    "GRACE_MAX_CACHE_AGE_DAYS",
    "fetch_ibtracs",
    "ensure_ibtracs_file",
    "ibtracs_url",
    "ibtracs_filename",
    "storm_cache_dir",
    "GageField",
    "GageRecord",
    "fetch_usgs",
    "usgs_cache_dir",
    "site_inventory_url",
    "dv_request_url",
    "USGS_SITE_BASE",
    "USGS_DV_BASE",
    "USGS_PARAMETERS",
    "USGS_MISSING",
    "USGS_RECORD_START",
    "USGS_MAX_CACHE_AGE_DAYS",
    "USGS_SITE_LIMIT",
    "COMCAT_EVENT_BASE",
    "COMCAT_COUNT_BASE",
    "COMCAT_RECORD_START",
    "COMCAT_FDSN_LIMIT",
    "COMCAT_PAGE_SIZE",
    "COMCAT_MAX_CACHE_AGE_DAYS",
    "COMCAT_DEPTH_BINS_KM",
    "QuakeEvent",
    "QuakeField",
    "comcat_cache_dir",
    "event_query_url",
    "event_count_url",
    "fetch_earthquakes",
    "FT3S_TO_M3S",
    "FT_TO_M",
    "sshs_category",
    "IBTRACS_VERSION",
    "IBTRACS_NC_DIR",
    "IBTRACS_SINCE1980_FILE",
    "IBTRACS_ALL_FILE",
    "IBTRACS_START_SINCE1980",
    "IBTRACS_START_ALL",
    "SSHS_CATEGORIES",
    "SSHS_COLORS",
    "SSHS_LABELS",
    "decode_concentration",
    "read_concentration_geotiff",
    "reproject_to_latlon",
    "resolve_native_grid",
    "ps_forward",
    "target_grid",
    "NSIDC_BASE",
    "NSIDC_G02135_PATH",
    "NSIDC_VERSION",
    "NSIDC_START",
    "NSIDC_GRIDS",
    "NSIDC_FLAGS",
    "NSIDC_FLAG_LABELS",
    "NSIDC_CONC_SCALE",
    "NSIDC_CELL_M",
    "HUGHES_A",
    "HUGHES_E2",
    "RainField",
    "ImergCredentialsMissing",
    "IMERG_BASE",
    "IMERG_VERSION",
    "IMERG_COLLECTIONS",
    "IMERG_START",
    "IMERG_LATENCY",
    "IMERG_RES",
    "IMERG_UNITS_DAILY",
    "IMERG_UNITS_NATIVE",
    "IMERG_FILL",
    "IMERG_ACCUMULATIONS",
    "fetch_imerg",
    "accumulate_daily",
    "imerg_granule_name",
    "imerg_file_url",
    "imerg_sample_days",
    "imerg_index_windows",
    "normalize_imerg_run",
    "normalize_imerg_accumulate",
    "mur_granule_title",
    "mur_opendap_url",
    "mur_subset_urls",
    "earthdata_credentials",
    "validate_sst_bbox",
    "Era5Field",
    "Era5CredentialsMissing",
    "ERA5_DATASET",
    "ERA5_START",
    "ERA5_RES",
    "ERA5_VARIABLES",
    "fetch_era5",
    "normalize_era5_variables",
    "validate_era5_bbox",
    "era5_area_windows",
    "era5_cds_names",
    "era5_month_chunks",
    "era5_request",
    "era5_sample_plan",
    "OSCAR_COLLECTIONS",
    "OSCAR_GRANULE_STEMS",
    "OSCAR_OPENDAP_PATTERN",
    "OSCAR_RES",
    "OSCAR_LON_MIN",
    "OSCAR_LON_MAX",
    "OSCAR_LAT_MIN",
    "OSCAR_LAT_MAX",
    "OSCAR_DIM_ORDER",
    "OSCAR_START",
    "OSCAR_FINAL_MAX_AGE_DAYS",
    "OSCAR_INTERIM_MAX_AGE_DAYS",
    "CMEMS_CURRENTS_PRESET",
    "CMEMS_CURRENTS_VARIABLES",
    "OscarCredentialsMissing",
    "fetch_oscar",
    "fetch_cmems_currents",
    "oscar_collection_for",
    "oscar_granule_title",
    "oscar_service_url",
    "cmr_search_oscar_granules",
    "oscar_lon_windows",
    "oscar_index_windows",
    "oscar_subset_urls",
    "oscar_synthetic",
    "cmems_currents_synthetic",
    "TopoField",
    "fetch_gebco",
    "fetch_naturalearth",
    "ensure_gebco_tile",
    "ensure_naturalearth_zip",
    "gebco_tiles_for_bbox",
    "synthetic_naturalearth",
    "GEBCO_VERSION",
    "GEBCO_ZIP_URL",
    "GEBCO_NATIVE_ARCSEC",
    "NATURAL_EARTH_SCALES",
    "NATURAL_EARTH_LAYERS",
    "OceanColorField",
    "fetch_oceancolor",
    "fetch_oceancolor_coastwatch",
    "fetch_oceancolor_cmems",
    "fetch_oceancolor_obpg",
    "obpg_file_names",
    "oceancolor_urls",
    "oceancolor_cache_dir",
    "OBPG_DIRECTACCESS_BASE",
    "OBPG_CMR_COLLECTION_ID",
    "OBPG_CMR_SHORT_NAME",
    "OBPG_RECORD_START",
    "COASTWATCH_ERDDAP_BASE",
    "COASTWATCH_DATASETS",
    "CMEMS_OCEANCOLOR_PRODUCT",
    "CMEMS_OCEANCOLOR_VARIABLE",
    "OCEANCOLOR_VAR",
    "OCEANCOLOR_UNITS",
    "OCEANCOLOR_LON_MIN",
    "OCEANCOLOR_LON_MAX",
    "OCEANCOLOR_LAT_MIN",
    "OCEANCOLOR_LAT_MAX",
    "OCEANCOLOR_MAX_CACHE_AGE_DAYS",
    "PROVENANCE_VERSION",
    "read_provenance",
    "verify_provenance",
    "write_provenance",
    "__version__",
]
